-- Practice my MySQL skills after self-study
-- (The database is generated by AI for practicing)
USE ecommerce_practice;

-- 1.Data Retrieval and Inner Join
SELECT 
	p.product_id,
    p.price,
    p.name AS product_name,
    c.name AS category_name
FROM products p 
JOIN categories c 
	USING (category_id)
WHERE p.price > 80 AND c.name LIKE 'Ele%'
ORDER BY price DESC;

-- 2.Find the best sellers
SELECT
	p.product_id,
    p.name AS product,
    c.name AS category,
	SUM(oi.quantity) AS sold_quantity
FROM order_items oi
JOIN products p USING (product_id)
JOIN categories c USING (category_id)
JOIN orders o USING (order_id)
WHERE o.status = 'completed'
GROUP BY product_id
ORDER BY sold_quantity DESC;

-- 3.Use Aggregate Functions And Subqueries
-- find customers buy more than average in 2023
SELECT 
	c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(oi.unit_price * oi.quantity) AS total_payment
FROM orders o 
JOIN order_items oi USING (order_id)
JOIN customers c USING (customer_id)
WHERE 
	o.ordered_at BETWEEN '2023-01-01' AND '2023-12-31'
    AND o.status = 'completed'
GROUP BY c.customer_id
HAVING total_payment >
	(
		SELECT AVG(unit_price * quantity) AS average_payment
		FROM orders
		JOIN order_items
			USING (order_id)
		WHERE 
			ordered_at BETWEEN '2023-01-01' AND '2023-12-31'
	)
ORDER BY total_payment DESC;

-- 4.Find customers who buy some products multiple times
SELECT 
	c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    p.name AS product_name,
    SUM(quantity) AS total_bought_quantity
FROM order_items oi
JOIN products p USING (product_id)
JOIN orders o USING (order_id)
JOIN customers c USING (customer_id)
WHERE o.status = 'completed'
GROUP BY p.product_id, c.customer_id
HAVING COUNT(quantity) > 1
ORDER BY total_bought_quantity DESC;

-- 5.Use the created View 
SELECT * FROM customer_spending_summary
ORDER BY total_spent DESC;

-- 6.Call the created Procedure
CALL get_customer_orders(1);

-- 7.Trigger Verification and Transaction
START TRANSACTION;
SELECT product_id, name, stock_quantity FROM products WHERE product_id = 1;
INSERT INTO orders (customer_id, status) 
	VALUES (1, 'pending');
INSERT INTO order_items (order_id, product_id, quantity, unit_price)
	VALUES (LAST_INSERT_ID(), 1, 17, 79.99);
SELECT product_id, name, stock_quantity FROM products WHERE product_id = 1;
ROLLBACK; -- There should be 117 and 100 for two SELECTs in result